#!/usr/bin/env bash

set -e

tool_source="${BASH_SOURCE[0]}"
while [ -h "$tool_source" ] ; do tool_source="$(readlink "$tool_source")"; done
sdlc_dir="$( cd -P "$( dirname "$tool_source" )" && pwd )"
prj_home="$( cd -P "$( dirname "$sdlc_dir" )" && pwd )"

cd "${prj_home}"

[[ -x ./mvnw ]] || {
  echo 'No Maven wrapper executable: aborting'
  exit 1
}

# Remote Repository Filtering:
# allows filtering of Artifact by RemoteRepository based on various criteria
# ${session.rootDirectory} is mvn placeholder, not a script variable
# https://maven.apache.org/resolver/remote-repository-filtering.html
./mvnw -s .mvn/settings.xml --update-snapshots --no-transfer-progress --batch-mode \
   '-Daether.remoteRepositoryFilter.groupId.basedir=${session.rootDirectory}/.mvn/rrf/' \
    -Daether.remoteRepositoryFilter.groupId=true \
     verify -Pci
